
export const styles = {
  dashboardContainer: { display: "flex", minHeight: "100vh", backgroundColor: "#f8fafc", fontFamily: "sans-serif", color: "#1e293b" },
  sidebar: { width: "280px", backgroundColor: "#0f172a", color: "#fff", display: "flex", flexDirection: "column", padding: "1.5rem" },
  sidebarBrand: { display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "2rem" },
  brandText: { fontSize: "1.4rem", fontWeight: "bold", background: "linear-gradient(to right, #3b82f6, #60a5fa)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" },
  profileSection: { display: "flex", flexDirection: "column", alignItems: "center", padding: "1rem", backgroundColor: "#1e293b", borderRadius: "12px", marginBottom: "2rem" },
  avatar: { fontSize: "2.5rem", marginBottom: "0.5rem" },
  profileName: { fontSize: "1.1rem", margin: "0.2rem 0" },
  statusBadge: { backgroundColor: "#10b981", fontSize: "0.75rem", padding: "0.2rem 0.6rem", borderRadius: "20px", fontWeight: "bold" },
  navMenu: { display: "flex", flexDirection: "column", gap: "0.5rem", flexGrow: 1 },
  navItem: { padding: "0.75rem 1rem", border: "none", borderRadius: "8px", backgroundColor: "transparent", color: "#94a3b8", textAlign: "left", cursor: "pointer", fontSize: "1rem", transition: "0.2s" },
  activeNav: { backgroundColor: "#3b82f6", color: "#fff", fontWeight: "bold" },
  logoutBtn: { backgroundColor: "#ef4444", color: "#fff", border: "none", padding: "0.75rem", borderRadius: "8px", cursor: "pointer", fontWeight: "bold" },
  mainContent: { flexGrow: 1, padding: "2rem" },
  topHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "2rem", borderBottom: "1px solid #e2e8f0", paddingBottom: "1rem" },
  headerMetrics: { display: "flex", gap: "1rem" },
  miniMetric: { padding: "0.5rem 1rem", backgroundColor: "#fff", border: "1px solid #e2e8f0", borderRadius: "8px" },
  card: { backgroundColor: "#fff", borderRadius: "12px", padding: "1.5rem", boxShadow: "0 4px 6px -1px rgb(0 0 0 / 0.05)", border: "1px solid #e2e8f0" },
  cardHeader: { display: "flex", justifyContent: "space-between", borderBottom: "1px solid #f1f5f9", paddingBottom: "1rem", marginBottom: "1rem" },
  liveIndicator: { color: "#ef4444", fontWeight: "bold", display: "flex", alignItems: "center", gap: "0.25rem", fontSize: "0.9rem" },
  tripId: { fontWeight: "bold", color: "#64748b" },
  tripGrid: { display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: "1.5rem", marginBottom: "1.5rem" },
  label: { fontSize: "0.75rem", color: "#64748b", fontWeight: "bold", textTransform: "uppercase", margin: 0 },
  value: { fontSize: "1.1rem", margin: "0.2rem 0", fontWeight: "500" },
  actionRow: { display: "flex", gap: "1rem" },
  primaryBtn: { backgroundColor: "#3b82f6", color: "#fff", border: "none", padding: "0.75rem 1.5rem", borderRadius: "8px", cursor: "pointer", fontWeight: "bold" },
  secondaryBtn: { backgroundColor: "#f1f5f9", color: "#1e293b", border: "1px solid #cbd5e1", padding: "0.75rem 1.5rem", borderRadius: "8px", cursor: "pointer", fontWeight: "bold" },
  tableWrapper: { overflowX: "auto", marginTop: "1rem" },
  table: { width: "100%", borderCollapse: "collapse", textAlign: "left" },
  th: { padding: "0.75rem", borderBottom: "2px solid #e2e8f0" },
  td: { padding: "0.75rem", borderBottom: "1px solid #e2e8f0" },
  tr: { transition: "0.2s" },
  tableBtn: { backgroundColor: "#10b981", color: "#fff", border: "none", padding: "0.4rem 0.8rem", borderRadius: "6px", cursor: "pointer", fontSize: "0.9rem", fontWeight: "bold" }
};
